### ISSUE TITLE
'import' and 'export' may appear only with 'sourceType: module

### ISSUE THREAD

**Issue by Darksymphony75** [sindresorhus/neat-csv#22]
After installing neat-csv 7.0.0. with Cypress 13.6.0 and @badeball/cypress-cucumber-preprocessor + @badeball/cypress-cucumber-preprocessor/browserify, when I add import neatCSV from "neat-csv"; to my test case, Cypress test runner says: 

```
SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (1:0) while parsing C:\Users\username\Desktop\Cypress\node_modules\neat-csv\index.js while parsing file: C:\Users\username\Desktop\Cypress\node_modules\neat-csv\index.js

at DestroyableTransform.end [as _flush] (C:\Users\username\Desktop\Cypress\node_modules\insert-module-globals\index.js:114:21)
    at DestroyableTransform.prefinish (C:\Users\username\Desktop\Cypress\node_modules\readable-stream\lib\_stream_transform.js:138:10)
    at DestroyableTransform.emit (node:events:514:28)
    at prefinish (C:\Users\username\Desktop\Cypress\node_modules\readable-stream\lib\_stream_writable.js:619:14)
    at finishMaybe (C:\Users\username\Desktop\Cypress\node_modules\readable-stream\lib\_stream_writable.js:627:5)
    at endWritable (C:\Users\username\Desktop\Cypress\node_modules\readable-stream\lib\_stream_writable.js:638:3)
    at DestroyableTransform.Writable.end (C:\Users\username\Desktop\Cypress\node_modules\readable-stream\lib\_stream_writable.js:594:22)
    at DestroyableTransform.onend (C:\Users\username\Desktop\Cypress\node_modules\readable-stream\lib\_stream_readable.js:577:10)
    at Object.onceWrapper (node:events:628:28)
    at DestroyableTransform.emit (node:events:526:35)
    at endReadableNT (C:\Users\username\Desktop\Cypress\node_modules\readable-stream\lib\_stream_readable.js:1010:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by sindresorhus** [comment]
The error already points out the problem. This has nothing to do with this package.
